// gemini.js
/**
 * Calls the Gemini API using standard fetch.
 */
export async function analyzeWithGemini(apiKey, modelName, systemPrompt, userPrompt) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

  // We'll use the schema to force JSON output
  const { analysisSchema } = await import('./schema.js');

  const payload = {
    contents: [
      {
        role: "user",
        parts: [{ text: userPrompt }]
      }
    ],
    systemInstruction: {
      role: "system",
      parts: [{ text: systemPrompt }]
    },
    generationConfig: {
      temperature: 0.1, // Even lower for maximum consistency
      topP: 0.95,
      topK: 40,
      maxOutputTokens: 4096, // Doubled to prevent truncation
      responseMimeType: "application/json",
      responseSchema: analysisSchema
    }
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `API request failed with status ${response.status}`);
  }

  const data = await response.json();
  
  if (!data.candidates || data.candidates.length === 0) {
    throw new Error('No response generated by the model.');
  }

  let resultText = data.candidates[0].content.parts[0].text;
  
  // Robustness check: strip markdown code fences if they accidentally appear
  resultText = resultText.replace(/^```json\n?/, '').replace(/\n?```$/, '').trim();
  
  try {
    return JSON.parse(resultText);
  } catch (err) {
    console.error('Raw result that failed to parse:', resultText);
    throw new Error(`Failed to parse AI response. The model might have truncated the output. Error: ${err.message}`);
  }
}
