// gemini.js
import { toolsDefinition, toolsImplementations } from './tools.js';

/**
 * Calls the Gemini API using standard fetch and supports multi-turn tool calling.
 */
export async function analyzeWithGemini(apiKey, modelName, systemPrompt, userPrompt, onReasoningStep) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

  // We'll use the schema to force JSON output for the final response
  const { analysisSchema } = await import('./schema.js');

  let contents = [
    {
      role: "user",
      parts: [{ text: userPrompt }]
    }
  ];

  const payload = {
    systemInstruction: {
      role: "system",
      parts: [{ text: systemPrompt + "\n\nYou MUST return your final response as a JSON object matching this schema:\n" + JSON.stringify(analysisSchema, null, 2) }]
    },
    tools: [{ functionDeclarations: toolsDefinition }],
    generationConfig: {
      temperature: 0,
      topP: 0.95,
      topK: 40,
      maxOutputTokens: 8192
    }
  };

  const MAX_TURNS = 10;
  let turnCount = 0;

  while (turnCount < MAX_TURNS) {
    turnCount++;
    // Turn 1: Force a tool call (ANY). Turns 2-5: Let agent choose (AUTO). Turn 6+: Force final answer (NONE).
    let toolConfigMode;
    if (turnCount === 1) {
      toolConfigMode = "ANY";
    } else if (turnCount <= 5) {
      toolConfigMode = "AUTO";
    } else {
      toolConfigMode = "NONE"; // Force the model to stop calling tools and produce final JSON
    }
    const currentToolConfig = { functionCallingConfig: { mode: toolConfigMode } };

    const requestPayload = { ...payload, contents, toolConfig: currentToolConfig };

    // When forcing NONE mode, add a nudge so the model knows to produce the final answer
    if (toolConfigMode === "NONE" && contents[contents.length - 1]?.role !== 'user') {
      contents.push({ role: 'user', parts: [{ text: 'You have gathered enough information. Now produce your final JSON analysis. Remember: respond ONLY with a raw JSON object starting with { and ending with }.' }] });
    }

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestPayload)
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error?.message || `API request failed with status ${response.status}`);
    }

    const data = await response.json();
    
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No response generated by the model.');
    }

    const candidate = data.candidates[0];
    
    if (candidate.finishReason && candidate.finishReason !== 'STOP') {
      console.warn('Non-STOP finish reason:', candidate);
      if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
        throw new Error(`Generation stopped with reason: ${candidate.finishReason}. No content returned.`);
      }
    }

    // Handle empty response (model produced no parts) - nudge it to continue
    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      console.warn('Empty response from model, nudging to continue...', candidate);
      contents.push({ role: 'user', parts: [{ text: 'Please continue. Use any remaining tools you need, then produce your final JSON analysis.' }] });
      continue;
    }

    const responsePart = candidate.content.parts[0];

    // Append model response to history
    contents.push(candidate.content);

    // Check if it's a function call
    if (responsePart.functionCall) {
      const call = responsePart.functionCall;
      
      if (onReasoningStep) {
        onReasoningStep(`Agent is calling tool: ${call.name}(${JSON.stringify(call.args)})`);
      }

      let toolResult;
      const toolFunction = toolsImplementations[call.name];
      if (toolFunction) {
        try {
          // If the tool takes multiple args, we could map them. All our tools take 1 arg named after the parameter.
          // Get the first value from the args object:
          const argValue = Object.values(call.args)[0];
          toolResult = await toolFunction(argValue);
        } catch (e) {
          toolResult = `Error executing tool: ${e.message}`;
        }
      } else {
        toolResult = `Tool ${call.name} not found.`;
      }

      if (onReasoningStep) {
        onReasoningStep(`Tool result: ${typeof toolResult === 'object' ? JSON.stringify(toolResult) : toolResult}`);
      }

      // Append function response to history
      contents.push({
        role: "function",
        parts: [{
          functionResponse: {
            name: call.name,
            response: typeof toolResult === 'object' ? toolResult : { result: toolResult }
          }
        }]
      });
      
      // Continue the loop to let the model respond to the tool result
      continue;
    }

    // If it's not a function call, it must be the final text answer
    let resultText = responsePart.text;
    
    // Robustness check: extract JSON block if there's conversational text
    const jsonMatch = resultText.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      resultText = jsonMatch[0];
    } else {
      // Model returned plain conversational text (e.g. "There are no math claims to verify...")
      // Nudge it to produce the final JSON instead of crashing
      console.warn('Model returned plain text instead of JSON, nudging...', resultText);
      contents.push({ role: 'user', parts: [{ text: 'Good. Now produce your final JSON analysis. Respond ONLY with a raw JSON object starting with { and ending with }.' }] });
      continue;
    }
    
    try {
      if (onReasoningStep) {
        onReasoningStep('Agent has completed analysis.');
      }

      // ── LLM CONVERSATION LOG ──────────────────────────────────────────
      // Copy this from DevTools Console for your assignment submission.
      console.group('%c🤖 See Through the Hype — Full LLM Conversation Log', 'color: #6366f1; font-weight: bold; font-size: 14px;');
      contents.forEach((turn, i) => {
        const role = turn.role?.toUpperCase() || 'UNKNOWN';
        const emoji = role === 'USER' ? '👤' : role === 'MODEL' ? '🤖' : '🔧';
        const part = turn.parts?.[0];
        if (part?.text) {
          console.log(`%c${emoji} Turn ${i + 1} [${role}]`, 'font-weight:bold; color:#94a3b8', '\n' + part.text.substring(0, 500));
        } else if (part?.functionCall) {
          console.log(`%c${emoji} Turn ${i + 1} [${role}] → Tool Call: ${part.functionCall.name}`, 'font-weight:bold; color:#f59e0b', '\nArgs:', JSON.stringify(part.functionCall.args, null, 2).substring(0, 300));
        } else if (part?.functionResponse) {
          console.log(`%c${emoji} Turn ${i + 1} [${role}] → Tool Result: ${part.functionResponse.name}`, 'font-weight:bold; color:#22c55e', '\nResult:', JSON.stringify(part.functionResponse.response, null, 2));
        }
      });
      console.log('%c📋 Full conversation (copy this):', 'font-weight:bold; color:#6366f1');
      console.log(JSON.stringify(contents, null, 2));
      console.groupEnd();
      // ─────────────────────────────────────────────────────────────────

      return JSON.parse(resultText);
    } catch (err) {
      console.error('Raw result that failed to parse:', resultText);
      if (err.message.toLocaleLowerCase().includes('unterminated') || 
          err.message.toLocaleLowerCase().includes('unexpected end of input')) {
        throw new Error('This page content was too large for the AI to analyze in one go.');
      }
      throw new Error(`Failed to parse AI response. Text was: "${resultText.substring(0, 40)}...". Error: ${err.message}`);
    }
  }

  throw new Error(`Exceeded maximum turns (${MAX_TURNS}) without reaching a final answer.`);
}
